spring:
  application:
    name: gateway-web
  redis:
    host: 192.168.211.132
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
             allowedOrigins: "*" #跨域处理 允许所有的域
             allowedMethods: #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
            - id: changgou_page_cart_route
              uri: lb://item
              predicates:
              - Path=/api/cart/showlist
              filters:
              - StripPrefix=1
            - id: changgou_delete_cart_route
              uri: lb://order
              predicates:
              - Path=/api/cart/delete/*
              filters:
              - StripPrefix=1

            - id: changgou_goods_route
              uri: lb://goods
              predicates:
              - Path=/api/goods/**
             # filters:
             # - PrefixPath=/brand
              filters:
              - StripPrefix=1
             # 局部限流过滤器
              - name: RequestRateLimiter
                args:
                  key-resolver: "#{@ipKeyResolver}"
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 4
            - id: changgou_user_route
              uri: lb://user
              predicates:
              - Path=/api/user/**,/api/address/**,/api/cities/**,/api/provinces/**
              filters:
              - StripPrefix=1
                 # 局部限流过滤器
              - name: RequestRateLimiter
                args:
                   key-resolver: "#{@ipKeyResolver}"
                   redis-rate-limiter.replenishRate: 1
                   redis-rate-limiter.burstCapacity: 4
            - id: changgou_order_route
              uri: lb://order
              predicates:
              - Path=/api/cart/add
              - Query=num
              filters:
              - StripPrefix=1
            - id: changgou_cart_route
              uri: lb://order
              predicates:
              - Path=/api/cart/list
              filters:
              - StripPrefix=1

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true