server:
  port: 18096
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: admin-web
  main:
    allow-bean-definition-overriding: true
  resources:
    static-locations: classpath:/static/