server:
  port: 18088
Spring:
  resources:
    static-locations: classpath:/
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
# feign:
  # hystrix:
    # enabled: true
  #hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  main:
    allow-bean-definition-overriding: true
# 生成静态页的位置
pagepath: D:\codes\ChangGou\changgou-parent\changgou-web\changgou-web-item\src\main\resources\static